test:
    host: $DATABASE_URL
    name: $DB_TEST_NAME
    user: $DB_USER
    password: $DB_PASSWORD
    pool: 0
    open: tcp:$DATABASE_URL:3306*$DB_TEST_NAME/$DB_USER/$DB_PASSWORD

development:
    host: $DATABASE_URL
    name: $DB_NAME
    user: $DB_USER
    password: $DB_PASSWORD
    pool: 5
    open: tcp:$DATABASE_URL:3306*$DB_NAME/$DB_USER/$DB_PASSWORD

production:
    host: $DATABASE_URL
    name: $DB_NAME
    user: $DB_USER
    password: $DB_PASSWORD
    pool: 5
    open: tcp:$DATABASE_URL:3306*$DB_NAME/$DB_USER/$DB_PASSWORD
